name: map4d_map
version: 2.2.1
description: A Flutter plugin for integrating Map4D in iOS and Android applications.
homepage: https://map4d.vn
repository: https://github.com/map4d/map4d-map-flutter
issue_tracker: https://github.com/map4d/map4d-map-flutter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: vn.map4d.map.map4d_map
        pluginClass: FMFMapViewPlugin
      ios:
        pluginClass: Map4dMapPlugin
